language: cpp
install:
- wget https://github.com/galeksandrp/zyxel-keenetic-packages/releases/download/v-oss/zyxel_keenetics_gpl_v.1.00_4_d0.tar_.bz2
  -O - | tar xj
- yes 'Yes' | zyxel_keenetics_gpl_v.1.00_4_D0/zyxel_keenetics_gpl_v.1.00_4_D0.lnx
  && rm zyxel_keenetics_gpl_v.1.00_4_D0 -rf
- cd zyxel_keenetics_gpl_v.1.00_4_D0_161111/include
- patch < ../../prereq-build.mk.patch
- cd ..
script:
- ./configure.sh keenetic
before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - echo version > $TRAVIS_COMMIT
  - echo -e "machine github.com\nlogin galeksandrp\npassword $GITHUB_TOKEN" >> ~/.netrc
  - git tag deploy-$(git describe --always) || true
  - git push --tags
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file: $TRAVIS_COMMIT
  overwrite: true
  on:
    all_branches: true
branches:
  except:
    - /^deploy-.*$/
notifications:
  email: false
